steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'AUTH_ORG', '--runtime', 'nodejs14', '--trigger-http', '--allow-unauthenticated', '--entry-point', 'app']
